# recebi erro sim, mas estou fazendo isso so por 'fazer

# codigo com erro de indice/index
# idiomas = ['latim', 'portugues', 'ingles', 'italiano']
# print(idiomas[4])

# codigo correto
idiomas = ['latim', 'portugues', 'ingles', 'italiano']
print(idiomas[3])